name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  name:
    required: true
    description: 'input name to greet'
    default: 'World'
runs:
  using: 'node12'
  main: 'dist/index.js'
